### ISSUE TITLE
[Suggestion] Mariculture Titanium Part Tooltips

### ISSUE THREAD

**Issue by SisterJacq** [squeek502/TiC-Tooltips#1]
Mariculture adds Titanium Tool Parts, so I am wondering if you could add support~
-Mortvana

**Comment by squeek502** [comment]
Will look into it.

**Comment by SisterJacq** [comment]
Cool~

**Comment by squeek502** [comment]
Thanks for suggesting it. If you know of any other mods that add Tinkers Construct parts, let me know.

**Comment by SisterJacq** [comment]
No problem, I will~
