### ISSUE TITLE
Integration with Iguanas Tinkers Tweaks missing

### ISSUE THREAD

**Issue by ghost** [squeek502/TiC-Tooltips#15]
I'm getting this with the latest version of Tinker Tweaks:

[TiCTooltips/TiCTooltips]: Failed to load Iguana Tweaks integration: java.lang.NoSuchMethodException: iguanaman.iguanatweakstconstruct.IguanaTweaksTConstruct.getHarvestLevelName(int)

Versions:
IguanaTinkerTweaks-1.7.10-2.0.2.jar
TiC-Tooltips-mc1.7.10-1.1.9.jar

**Comment by squeek502** [comment]
Will be fixed next version. Thanks for letting me know. Will keep this open until I push the commit that fixes it.

**Comment by ghost** [comment]
Been tinkering with this and found a solution. I didn't test it with TiC-Tooltips because I couldn't get it to build but it works with WailaHarvestability which uses the same code here:

In: ProxyIguanaTweaks.java

Change: IguanaTweaksTConstruct = Class.forName("iguanaman.iguanatweakstconstruct.IguanaTweaksTConstruct");

To: IguanaTweaksTConstruct = Class.forName("iguanaman.iguanatweakstconstruct.util.HarvestLevels");

**Comment by squeek502** [comment]
Thanks, I had the fix already written locally but just hadn't pushed it yet.
