### ISSUE TITLE
Extra strings needed

### ISSUE THREAD

**Issue by labpaw** [squeek502/TiC-Tooltips#17]
I need extra strings for "tictooltips.tool.repair.material=Repair Material:" for all materials. http://i.imgur.com/yKQVWe5.jpg actually it uses adjective ("Медная" for example) but it should use noun("Медь"). So, it shouldn't be hard to add extra strings(or maybe make them optional)

**Comment by squeek502** [comment]
That string is from Tinkers Construct (I'm simply using `material.localizedName()`, which gets the `material.<materialname>` string).

It looks like you should make all `material.<materialname>` strings the noun version, and then add `material.<materialname>.display` strings for the adjective versions (currently, the `material.<materialname>` versions only get used for [displaying the current material in the part crafter GUI](https://github.com/SlimeKnights/TinkersConstruct/blob/80efde613ac73e98279e1ab8adb1107638f1a0e4/src/main/java/tconstruct/tools/gui/PartCrafterGui.java#L72), and the `material.<materialname>.display` versions only get used for [default tool names](https://github.com/SlimeKnights/TinkersConstruct/blob/72fdecbfd2ee47931da7b84bf0998dd7da7563bc/src/main/java/tconstruct/library/crafting/ToolBuilder.java#L442)).

**Comment by labpaw** [comment]
Can you show up me few specific examples? I don't really know that I should add :smile:

**Comment by squeek502** [comment]
In the Tinkers Construct lang files, you should update the [material strings](https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/lang/en_US.lang#L769-L800).

For example, if you want the noun version of Copper to be displayed by TiC Tooltips' "Repair Material" string, you would set:

```
material.copper=Медь
material.copper.display=Медная
```

Note: `material.copper.display` is only used if `tool.<tooltype>.<material>` doesn't exist.

**Comment by labpaw** [comment]
Sorry for wasting your time. I understood :smile:

**Comment by squeek502** [comment]
I don't see how that can be the case. The `material.copper` string is **only** used for "Repair Material" and the part builder GUI (e.g. it says "Copper" on the right hand side when you put a piece of copper in), so I don't see how you'd need two different strings for those two things. They are describing the same thing (a material in the noun form), aren't they?

**Comment by labpaw** [comment]
I'm updated my comment. Sorry again.

**Comment by squeek502** [comment]
No worries. :)
