### ISSUE TITLE
Some issues with TiCTooltips-mc1.7.10-1.1.11b

### ISSUE THREAD

**Issue by psychofad** [squeek502/TiC-Tooltips#21]
To start I am using the following combination:
TConstruct-1.7.10-1.7.0d2
TiCTooltips-mc1.7.10-1.1.11b
IguanaTinkerTweaks-1.7.10-2.0.5

Ok so first thing, I was attempting to upgrade my handle and decided to look at the materials on my tool to see what the handle modifier was while in the part builder GUI and this happened:

http://pastebin.com/WE94yuQW

So I restarted my client...logged back into my server and tried to look at it without being in the GUI and when I press CTRL to see the materials it says Unnamed and has no info.

See this link for some screenshots:
http://imgur.com/a/sCV3W

This is happening on all of my tools that have Quicksilver heads.  Not sure if that matters.  I had an old tool in a chest...got it out and pressed CTRL on it and the material list displays as it should so it may just be choking on the metallurgy tool parts.  Let me know if I can provide any more information as I can reproduce the crash on demand.

**Comment by psychofad** [comment]
This is the crash as it appears in the log file:
http://pastebin.com/43BqGWQh

**Comment by squeek502** [comment]
Will look into it, thanks.

**Comment by psychofad** [comment]
This seems to be fixed when updating Tinkers Construct to the newest release 
TConstruct-1.7.10-1.7.0d3.1

There was a note in the changelog about localization stuff.  Feel free to close this issue if no one objects :D

**Comment by squeek502** [comment]
This is a symptom of https://github.com/SlimeKnights/TinkersConstruct/issues/1077
