### ISSUE TITLE
Add support for Tinkers' Gregworks

### ISSUE THREAD

**Issue by squeek502** [squeek502/TiC-Tooltips#22]
https://github.com/Vexatos/TinkersGregworks

Might be complicated.

**Comment by squeek502** [comment]
Closing as it seems like the project is dormant. Will reopen if starts being developed again.

**Comment by squeek502** [comment]
Seems to have active development again. Need to check if any special compat is needed.

**Comment by squeek502** [comment]
Looks like @Vexatos already added integration with TiC Tooltips: https://github.com/Vexatos/TinkersGregworks/blob/master/src/main/java/vexatos/tgregworks/integration/tictooltips/IntegrationTiCTooltips.java 

:+1:

**Comment by Vexatos** [comment]
:+1: Thanks for having looked into it anyway. However, adding integration myself was quite easy thanks to the way your mod is done ;)
