### ISSUE TITLE
Another localization change

### ISSUE THREAD

**Issue by labpaw** [squeek502/TiC-Tooltips#23]
http://i.imgur.com/GiQqh4p.jpg is it possible to make it looking for "material.wood.display" in Tinkers Construct .lang file instead of material.wood? For all materials of course :smile:

**Comment by squeek502** [comment]
I changed that to use the display name of the part in 1.1.11b, so it should show the same name as the part itself (see: https://github.com/squeek502/TiC-Tooltips/blob/1.7.10/java/squeek/tictooltips/TooltipHandler.java#L640-L641).

However, the linked code doesn't seem to work right with ExtraTiC (#21), so I'll probably have to revise it anyway.

Is the name of an actual wooden part different from what it shows in that tooltip?

**Comment by labpaw** [comment]
Yes, it is wood part but should be wooden.

**Comment by labpaw** [comment]
Still a problem...

**Comment by squeek502** [comment]
I meant to ask: Does the wooden pickaxe head item itself show as "Wood Pickaxe Head" in default Tinkers Construct? I just checked, and it does. Therefore, this is a Tinkers Construct bug.

See: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/items/ToolPart.java#L26-L43
