### ISSUE TITLE
Add support for TiC 1.8.x

### ISSUE THREAD

**Issue by SinusoidalC** [squeek502/TiC-Tooltips#28]
PLZ done it ASAP.

**Comment by squeek502** [comment]
Planning on it, but I'll likely have to break backwards compatibility with older TiC versions to do it.

**Comment by psychofad** [comment]
I would just go ahead and break the backwards compatibility and make it require 1.8.x or higher as anyone using an older version of TiC shouldn't need to update as the current version of TiC Tooltips works just fine with those versions. My 2 cents anyways. :D

**Comment by squeek502** [comment]
Yep, that's what I'm going to do. Been working on it the past few days, but it's taking a lot more effort than I expected, unfortunately.

**Comment by squeek502** [comment]
[Did done it](https://github.com/squeek502/TiC-Tooltips/releases/tag/v1.2.0).

**Comment by psychofad** [comment]
You're an animal! Happy New Year!
