### ISSUE TITLE
Crash when clicking search tab in creative with ExtrabiomesXL installed.

### ISSUE THREAD

**Issue by ghost** [squeek502/TiC-Tooltips#30]
Had this crash after updating TiCTooltips-mc1.7.10-1.1.11b to TiCTooltips-mc1.7.10-1.2.0 in a modpack I am working on currently.

I narrowed it down some...

With only the following mods installed;

-forge-1.7.10-10.13.2.1277-universal.jar
-Mantle-1.7.10-0.3.2.jar
-TConstruct-1.7.10-1.8.1.jar
-TiCTooltips-mc1.7.10-1.2.0.jar
-extrabiomesxl_1.7.10-3.16.0.jar

I get the following "shutting down internal server" warning crash.
http://pastebin.com/EJHGt82m

**Comment by squeek502** [comment]
Ah, I think I know why that's happening. Probably worth reporting to [ExtraBiomesXL](https://github.com/ExtrabiomesXL/ExtrabiomesXL) as well because it definitely shouldn't be possible to crash from calling getUnlocalizedName(), even if TiC Tooltips is doing something slightly incorrect (getting the name of a stack with OreDictionary.WILDCARD_VALUE metadata).

**Comment by ghost** [comment]
Done, and the response. Also, thank you for your prompt response. :D

" ScottKillen commented a minute ago

NotEnoughItems does the same thing...but Chickenbones anticipates a possible crash and catches the exception... If TIC Tooltips is going to pass potentially bad data, it should anticipate an exception and handle it."

**Comment by Udaldor** [comment]
I understand this won't be fixed on the TiC Tooltips side of things, right? That's a shame. ExtraBiomesXL doesn't update very often, and this is the only problem I've seen with it.

**Comment by squeek502** [comment]
Not sure where you got that impression. It has been fixed on my end (see the commit that closed this issue linked above), and I will release a version with the fix later today.

**Comment by Udaldor** [comment]
Sorry about that, I got the wrong impression from "worth reporting it to ExtraBiomesXL". Excuse my sillyness! :)

**Comment by squeek502** [comment]
:smile:
