### ISSUE TITLE
ExtraTiC names problem

### ISSUE THREAD

**Issue by labpaw** [squeek502/TiC-Tooltips#35]
TiC tooltips removes dots in some ExtraTiC names. ExtraTiC .lang file: https://github.com/Glassmaker/ExtraTiC-Localization/blob/master/en_US.lang#L60

**Comment by Adaptivity** [comment]
Ignore this. Was magically fixed after restart.

**Comment by labpaw** [comment]
Magical transformation.

**Comment by squeek502** [comment]
This would be an ExtraTiC issue, as I simply call ToolMaterial.localizedName().

https://github.com/squeek502/TiC-Tooltips/blob/1.7.10/java/squeek/tictooltips/helpers/CompatibilityHelper.java#L18

If only ExtraTiC was open source (@Glassmaker)...
