### ISSUE TITLE
Open-source licensing

### ISSUE THREAD

**Issue by asiekierka** [squeek502/TiC-Tooltips#4]
I noticed that your mod is on GitHub, but does not come with a license. This by default means that all rights are reserved to you. The CurseForge page, though, claims that it is licensed under the LGPLv3 - you might want to include a proper LICENSE file in your repository so it is easier to find.

**Comment by squeek502** [comment]
Appreciate the concern. I don't really know or care much about licensing, and the LGPLv3 license was something of a random choice. 

I've changed the license on my CurseForge projects to Public Domain. Unsure if I should include a LICENSE file in the repo still or not; if so it'd be the [Unlicense](http://unlicense.org/).
