### ISSUE TITLE
Extra TiC Compatibility

### ISSUE THREAD

**Issue by chrisk123999** [squeek502/TiC-Tooltips#42]
[Extra TiC](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445212-extratic-tinkers-construct-mod-support-add-on) just updated and added a bunch of new materials for Tinkers Construct.  Just tested and it doesn't look like this mod picks them up.

**Comment by squeek502** [comment]
Thanks for the heads up.

**Comment by squeek502** [comment]
@chrisk123999, can you post a screenshot of something that's not working for you? Everything seems to be fine on my end.

EDIT: Nevermind, it's the new weaponry parts that don't get tooltips. Will fix.
