### ISSUE TITLE
Localization improvements

### ISSUE THREAD

**Issue by labpaw** [squeek502/TiC-Tooltips#43]
Got some time to recheck localization.
1) _tictooltips.tool.shoddiness.modifier_ should be splitted to one string for Stonebound and one for Jagged modifiers.
2) Min and Max strings should have their own "Bonus" and "Loss" strings. Strings from Tcon doesn't fit there are very well in Russian language for example. They also should be _easy-to-swap_, so I can swap they as I need.
In general, I need to change all tooltips like that to something like _Min Loss "modifier name"_. How many modifiers affected by these tooltips? Stonebound and jagged, anything else? Because I need to correct modifier name on these tooltips too... because, well, it's the only way to make it properly.

**Comment by squeek502** [comment]
Yeah, I was thinking this might be an issue. I'll try to make it so that everything is more friendly for non-English languages.

**Comment by squeek502** [comment]
Let me know if 5b08ea3a7625391e0e929bbe35cee5377d9e6d4a addresses everything you had in mind.

**Comment by labpaw** [comment]
Thank you. Much better now but I need to modify these [strings](https://github.com/squeek502/TiC-Tooltips/blob/1.7.10/resources/assets/tictooltips/lang/en_US.lang#L32-L40) entirely as well as the modifiers names in them because in Russian language for example, only first word are capitalized. Other words are lowercase. And what about _Min_ strings, where they used?

**Comment by squeek502** [comment]
You _can_ edit those strings entirely; the `%s`'s can simply be replaced with the actual localized text. Example:

```
tictooltips.tool.stonebound.loss=Your String
```

Turns out the Min string is not currently used at all. I guess I just added it because I thought it might be used in the future.

**Comment by labpaw** [comment]
Ok, well. I'll test everything later in-game and let you now if everything clear.
