### ISSUE TITLE
Rearranging Mining Levels

### ISSUE THREAD

**Issue by ghost** [squeek502/TiC-Tooltips#52]
I've done some significant alterations of my current Iguana's Tinker Tweaks configuration in order to swap iron and tin in its default progression (as tin is softer than iron, and the bronze age came before the iron age... probably not the most logical reasons, but the order makes the most sense to me, at least).

The problem is, although I changed the level names and overrode all the affected tools, materials, and blocks, the tooltip still refers to the now-iron level as "tin," and the now-tin level as "iron."  Is there a configuration option for TiC Tooltips that allows me to correct this?  Where does it get its harvest level information from?

**Comment by squeek502** [comment]
Which tool are you testing this with? 

The problem doesn't seem like it'd be on my end for two reasons:
- I don't actually add a harvest level tooltip when Iguana Tweaks is installed; I let Iguana Tweaks take care of it. [Relevant code](https://github.com/squeek502/TiC-Tooltips/blob/c2fe0c1d4d5b30577ba39260bac1ec20ab4899c3/java/squeek/tictooltips/TooltipHandler.java#L550-L555).
- When I _do_ add a harvest level tooltip, I use [the provided API from Tinkers Construct](https://github.com/squeek502/TiC-Tooltips/blob/c2fe0c1d4d5b30577ba39260bac1ec20ab4899c3/java/squeek/tictooltips/helpers/StringHelper.java#L16), which means that it should get the correct string from Iguana Tweaks.

You may want to try removing TiC Tooltips and see if the bug persists. If so, it'd be an Iguana Tinkers Tweaks bug.

**Comment by ghost** [comment]
Thanks.  I kinda assumed, since it was a tooltip issue, that it was this mod.  We all know what happens when one assumes, right? :P

UPDATE: You're right.  It's still there with this mod uninstalled.  I'll take it to the correct repository.  Thanks for the help!

**Comment by squeek502** [comment]
No problem!
